version: "3.9"

services:
  chat-mysql:
    image: mysql:8.0
    container_name: chat-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatdb
    ports:
      - "3306:3306"
    volumes:
      - ./src/Chat.DB/Data/MySql:/var/lib/mysql
      - ./src/Chat.DB/Data/Backup:/backup
    command: [
      "--default-authentication-plugin=mysql_native_password"
    ]

  chat-api:
    build: .
    container_name: chat-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DatabaseConnection: "server=chat-mysql;port=3306;user=root;password=root;database=chatdb"
    depends_on:
      - chat-mysql
    ports:
      - "5000:8080"
